name: Run Domain Processing Script

on:
  push:
    paths:
      - 'DomainAbuse_Automation/Upload Your Domain List Here/*.txt'  # Triggers the action when a .txt file is pushed in the specific folder

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the Python script
      env:
        VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
        IPVOID_API_KEY: ${{ secrets.IPVOID_API_KEY }}
        WHOISJSON_API_KEY: ${{ secrets.WHOISJSON_API_KEY }}
      run: |
        mkdir -p DomainAbuse_Automation/result
        for file in DomainAbuse_Automation/Upload\ Your\ Domain\ List\ Here/*.txt; do
          echo "Processing $file"
          python domainabuse_script.py "$file" DomainAbuse_Automation/result
        done

    - name: Upload the results
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: DomainAbuse_Automation/result/  # Path to the folder where your script saves the CSV file

    - name: Clean up
      if: success()
      run: |
        rm DomainAbuse_Automation/Upload\ Your\ Domain\ List\ Here/*.txt
