name: Process Domains

on:
  push:
    paths:
      - "*.txt"

jobs:
  process_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run domain abuse script
        run: |
          python domainabuse_script.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add *.csv
          git commit -m "Add processed domain results"
          git push

      - name: Delete original txt file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm *.txt
          git add -u
          git commit -m "Remove processed txt files"
          git push
